name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm i

      - name: Check for Errors
        run: pnpm check

      - name: Lint
        run: pnpm lint

      - name: Commit Lint
        run: pnpm commitlint -l -V
